### ISSUE TITLE
CI step "Install sql cli" takes ages

### ISSUE THREAD

**Issue by amotl** [flow-heater/flow-heater#24]
Hi Tim,

this guy currently takes quite a while to compile. Apparently, the outcome is not cached.

![image](https://user-images.githubusercontent.com/453543/103575287-c5e23600-4ed1-11eb-80b5-858555ec58d3.png)

Maybe we can add it as a real dependency into one of the `Cargo.toml` files instead of invoking `cargo install sqlx-cli` in order to benefit from the [Rust Cache Action](https://github.com/marketplace/actions/rust-cache) we introduced just recently?

With kind regards,
Andreas.

**Comment by elbart** [comment]
Thanks a lot for the remark. I was observing this too however the problems are:
- the `cargo build` target wouldn't work without sqlx_cli having run the db creation + migration before that
- the caching does seem to have a download cache, which also works for `~/.cargo` folder, so the downloads are cached, but the build isn't
- the caching doesn't cache any of the compiled crates (neither for `cargo install sqlx_cli`, nor for `cargo build`)

I thought of providing our own GH action for this, I don't have an idea. I found [this][1] and would like to check this as a possibility.

[1]: https://github.com/actions/cache/blob/master/examples.md#rust---cargo

**Comment by elbart** [comment]
@amotl  Works now. The diff is here: https://github.com/flow-heater/fh-core/pull/18/files#diff-73e17259d77e5fbef83b2bdbbe4dc40a912f807472287f7f45b77e0cbf78792d
